# Data Transformation

Once your data is clean, the next step is to **reshape, reformat, and reorder** it as needed for analysis. Pandas gives you plenty of flexible tools to do this.

---

## Sorting & Ranking

### Sort by Values

```python
df.sort_values("Age")                   # Ascending sort
df.sort_values("Age", ascending=False)  # Descending
df.sort_values(["Age", "Salary"])       # Sort by multiple columns
```
df.sort_values(["Age", "Salary"]) sorts the DataFrame first by the "Age" column, and if there are ties (i.e., two or more rows with the same "Age"), it will sort by the "Salary" column.

### Reset Index
If you want the index to start from 0 and be sequential, you can reset it using reset_index()
```python
df.reset_index(drop=True, inplace=True)  # Reset the index and drop the old index
```
### Sort by Index

```python
df.sort_index()
```
The df.sort_index() function is used to sort the DataFrame based on its index values. If the index is not in a sequential order (e.g., you have dropped rows or performed other operations that change the index), you can use sort_index() to restore it to a sorted order.
### Ranking
The .rank() function in pandas is used to assign ranks to numeric values in a column, like scores or points. By default, it gives the average rank to tied values, which can result in decimal numbers. For example, if two people share the top score, they both get a rank of 1.5. You can customize the ranking behavior using the method parameter. One useful option is method='dense', which assigns the same rank to ties but doesn’t leave gaps in the ranking sequence. This is helpful when you want a clean, consecutive ranking system without skips.
```python
df["Rank"] = df["Score"].rank()                 # Default: average method
df["Rank"] = df["Score"].rank(method="dense")   # 1, 2, 2, 3
```

---

## Renaming Columns & Index

```python
df.rename(columns={"oldName": "newName"}, inplace=True)
df.rename(index={0: "row1", 1: "row2"}, inplace=True)
```

To rename all columns:

```python
df.columns = ["Name", "Age", "City"]
```

---

## Changing Column Order

Just pass a new list of column names:

```python
df = df[["City", "Name", "Age"]]   # Reorder as desired
```

You can also move one column to the front:

```python
cols = ["Name"] + [col for col in df.columns if col != "Name"]
df = df[cols]
```

---



## Summary

- Sort, rank, and rename to prepare your data    
- Reordering and reshaping are key for EDA and visualization

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023.0,Action,1050.0,7.2
1,Salman Khan,Tiger Zinda Hai,2017.0,Action,565.0,6.0
2,Aamir Khan,Dangal,2016.0,Biography,2024.0,8.4
3,Ranbir Kapoor,Brahmastra,2022.0,Fantasy,431.0,5.6
4,Ranveer Singh,Padmaavat,2018.0,Historical,585.0,7.0
5,Ayushmann Khurrana,Andhadhun,2018.0,Thriller,111.0,8.3
6,Rajkummar Rao,Stree,2018.0,Horror Comedy,180.0,7.5
7,Hrithik Roshan,War,2019.0,Action,475.0,6.5
8,Akshay Kumar,Good Newwz,2019.0,Comedy,318.0,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022.0,Horror Comedy,266.0,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017.0,Romantic Comedy,201.0,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019.0,Action,342.0,8.2
12,//djskdladjkdv,NaN,NaN,NaN,NaN,NaN

In [4]:
df.sort_values("Year")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016.0,Biography,2024.0,8.4
1,Salman Khan,Tiger Zinda Hai,2017.0,Action,565.0,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017.0,Romantic Comedy,201.0,6.1
4,Ranveer Singh,Padmaavat,2018.0,Historical,585.0,7.0
5,Ayushmann Khurrana,Andhadhun,2018.0,Thriller,111.0,8.3
6,Rajkummar Rao,Stree,2018.0,Horror Comedy,180.0,7.5
7,Hrithik Roshan,War,2019.0,Action,475.0,6.5
8,Akshay Kumar,Good Newwz,2019.0,Comedy,318.0,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019.0,Action,342.0,8.2
3,Ranbir Kapoor,Brahmastra,2022.0,Fantasy,431.0,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022.0,Horror Comedy,266.0,5.9
0,Shah Rukh Khan,Pathaan,2023.0,Action,1050.0,7.2
12,//djskdladjkdv,NaN,NaN,NaN,NaN,NaN

In [5]:
df.sort_values("Year", ascending=False)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023.0,Action,1050.0,7.2
3,Ranbir Kapoor,Brahmastra,2022.0,Fantasy,431.0,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022.0,Horror Comedy,266.0,5.9
7,Hrithik Roshan,War,2019.0,Action,475.0,6.5
8,Akshay Kumar,Good Newwz,2019.0,Comedy,318.0,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019.0,Action,342.0,8.2
4,Ranveer Singh,Padmaavat,2018.0,Historical,585.0,7.0
5,Ayushmann Khurrana,Andhadhun,2018.0,Thriller,111.0,8.3
6,Rajkummar Rao,Stree,2018.0,Horror Comedy,180.0,7.5
1,Salman Khan,Tiger Zinda Hai,2017.0,Action,565.0,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017.0,Romantic Comedy,201.0,6.1
2,Aamir Khan,Dangal,2016.0,Biography,2024.0,8.4
12,//djskdladjkdv,NaN,NaN,NaN,NaN,NaN

In [6]:
df2 = df.sort_values(["Year", "IMDb"]).copy()

In [7]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016.0,Biography,2024.0,8.4
1,Salman Khan,Tiger Zinda Hai,2017.0,Action,565.0,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017.0,Romantic Comedy,201.0,6.1
4,Ranveer Singh,Padmaavat,2018.0,Historical,585.0,7.0
6,Rajkummar Rao,Stree,2018.0,Horror Comedy,180.0,7.5
5,Ayushmann Khurrana,Andhadhun,2018.0,Thriller,111.0,8.3
7,Hrithik Roshan,War,2019.0,Action,475.0,6.5
8,Akshay Kumar,Good Newwz,2019.0,Comedy,318.0,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019.0,Action,342.0,8.2
3,Ranbir Kapoor,Brahmastra,2022.0,Fantasy,431.0,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022.0,Horror Comedy,266.0,5.9
0,Shah Rukh Khan,Pathaan,2023.0,Action,1050.0,7.2
12,//djskdladjkdv,NaN,NaN,NaN,NaN,NaN

In [8]:
df2.sort_index()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023.0,Action,1050.0,7.2
1,Salman Khan,Tiger Zinda Hai,2017.0,Action,565.0,6.0
2,Aamir Khan,Dangal,2016.0,Biography,2024.0,8.4
3,Ranbir Kapoor,Brahmastra,2022.0,Fantasy,431.0,5.6
4,Ranveer Singh,Padmaavat,2018.0,Historical,585.0,7.0
5,Ayushmann Khurrana,Andhadhun,2018.0,Thriller,111.0,8.3
6,Rajkummar Rao,Stree,2018.0,Horror Comedy,180.0,7.5
7,Hrithik Roshan,War,2019.0,Action,475.0,6.5
8,Akshay Kumar,Good Newwz,2019.0,Comedy,318.0,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022.0,Horror Comedy,266.0,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017.0,Romantic Comedy,201.0,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019.0,Action,342.0,8.2
12,//djskdladjkdv,NaN,NaN,NaN,NaN,NaN

In [9]:
df = df[["Film", "Actor", "Year", "Genre", "IMDb", "BoxOffice(INR Crore)"]]

In [10]:
df

,Film,Actor,Year,Genre,IMDb,BoxOffice(INR Crore)
0,Pathaan,Shah Rukh Khan,2023.0,Action,7.2,1050.0
1,Tiger Zinda Hai,Salman Khan,2017.0,Action,6.0,565.0
2,Dangal,Aamir Khan,2016.0,Biography,8.4,2024.0
3,Brahmastra,Ranbir Kapoor,2022.0,Fantasy,5.6,431.0
4,Padmaavat,Ranveer Singh,2018.0,Historical,7.0,585.0
5,Andhadhun,Ayushmann Khurrana,2018.0,Thriller,8.3,111.0
6,Stree,Rajkummar Rao,2018.0,Horror Comedy,7.5,180.0
7,War,Hrithik Roshan,2019.0,Action,6.5,475.0
8,Good Newwz,Akshay Kumar,2019.0,Comedy,7.0,318.0
9,Bhool Bhulaiyaa 2,Kartik Aaryan,2022.0,Horror Comedy,5.9,266.0
10,Badrinath Ki Dulhania,Varun Dhawan,2017.0,Romantic Comedy,6.1,201.0
11,Uri: The Surgical Strike,Vicky Kaushal,2019.0,Action,8.2,342.0
12,NaN,//djskdladjkdv,NaN,NaN,NaN,NaN