# Reading & Writing Files in Pandas

## CSV Files

### Read CSV
```python
df = pd.read_csv("data.csv")
```

Options:
```python
pd.read_csv("data.csv", usecols=["Name", "Age"], nrows=10)
```

### Write CSV
```python
df.to_csv("output.csv", index=False)
```

---

## Excel Files

### Read Excel
```python
df = pd.read_excel("data.xlsx")
```

Options:
```python
pd.read_excel("data.xlsx", sheet_name="Sales")
```

### Write Excel
```python
df.to_excel("output.xlsx", index=False)
```

Multiple sheets:
```python
with pd.ExcelWriter("report.xlsx") as writer:
    df1.to_excel(writer, sheet_name="Summary", index=False)
    df2.to_excel(writer, sheet_name="Details", index=False)
```

---

## JSON Files

### Read JSON
```python
df = pd.read_json("data.json")
```


## Summary

- `read_*` and `to_*` methods for CSV, Excel, JSON
- Use `sheet_name` for Excel

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023.0,Action,1050.0,7.2
1,Salman Khan,Tiger Zinda Hai,2017.0,Action,565.0,6.0
2,Aamir Khan,Dangal,2016.0,Biography,2024.0,8.4
3,Ranbir Kapoor,Brahmastra,2022.0,Fantasy,431.0,5.6
4,Ranveer Singh,Padmaavat,2018.0,Historical,585.0,7.0
5,Ayushmann Khurrana,Andhadhun,2018.0,Thriller,111.0,8.3
6,Rajkummar Rao,Stree,2018.0,Horror Comedy,180.0,7.5
7,Hrithik Roshan,War,2019.0,Action,475.0,6.5
8,Akshay Kumar,Good Newwz,2019.0,Comedy,318.0,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022.0,Horror Comedy,266.0,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017.0,Romantic Comedy,201.0,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019.0,Action,342.0,8.2
12,//djskdladjkdv,NaN,NaN,NaN,NaN,NaN

In [4]:
df = df[df['IMDb']>6.0]

In [5]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023.0,Action,1050.0,7.2
2,Aamir Khan,Dangal,2016.0,Biography,2024.0,8.4
4,Ranveer Singh,Padmaavat,2018.0,Historical,585.0,7.0
5,Ayushmann Khurrana,Andhadhun,2018.0,Thriller,111.0,8.3
6,Rajkummar Rao,Stree,2018.0,Horror Comedy,180.0,7.5
7,Hrithik Roshan,War,2019.0,Action,475.0,6.5
8,Akshay Kumar,Good Newwz,2019.0,Comedy,318.0,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017.0,Romantic Comedy,201.0,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019.0,Action,342.0,8.2

In [6]:
df.to_csv("data_updated.csv", index=False)

In [7]:
df = pd.read_json("my.json")

FileNotFoundError: File my.json does not exist

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 11
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Actor                 9 non-null      object
 1   Film                  9 non-null      object
 2   Year                  9 non-null      float64
 3   Genre                 9 non-null      object
 4   BoxOffice(INR Crore)  9 non-null      float64
 5   IMDb                  9 non-null      float64
dtypes: float64(3), object(3)
memory usage: 504.0+ bytes

In [9]:
data = [
    {"id": 1, "name": "Alice", "address": {"city": "Delhi", "zipcode": "110001"}},
    {"id": 2, "name": "Bob", "address": {"city": "Mumbai", "zipcode": "400001"}}
]